VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsEmpty"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' clsEmpty

' empty classes (classes without specific methods)
' In this module: empty routines created by '#nomethod,name...
' Adding an interface here will add the interface to the mcolKnownInterfaces collection,
' avoiding this interface to be listed in the "Interfaces not yet implemented" form


'Public mcolPrinted As Collection

' List of Interfaces without properties:

'#nomethod,IJHgrPipeSupport,IJRteCableSegmentPathFeat,IJRteCompOccur
'#nomethod,IJDGeometry,IJLocalCoordinateSystem
'#nomethod,IJRteCablewayCommon,IJRteCablewayStraightPathFeat,IJRteHeaderPathFeat
'#nomethod,IJRteMaxCableFillInfo,IJWBSItemChild,IJWBSProjectChild
'#nomethod,IJRteCableTrayOccur
'#nomethod,IJCoatingInfo
'#nomethod,IJCUHASHgrAisc_CO
'#nomethod,IJHgrChild
'#nomethod,IJHgrComponentItem
'#nomethod,IJHgrSupportItem
'#nomethod,IJUAHgrMiterOcc
'#nomethod,IJUAHgrOccLength
'#nomethod,IJUAHgrOccOverLength
'#nomethod,IJUAHgrOccStructuralPart
'#nomethod,IJHgrBOMDefinition
'#nomethod,IJUAHgrCardinalPointProp
'#nomethod,IJHgrDesignSupport
'#nomethod,IJUASlabCompositionType,ISPSSlabClassification,IJUASlabGeneralType
'#nomethod,IJGraphicEntity,IJRteCablewayEndPathFeat
'#nomethod,IJAppConnectionNotification,IJConstructionInfo,IJCUHASPipeDesignedO
'#nomethod,IJFabricationInfo,IJHgrMirrorReflectBits,IJHgrRestraintProperties
'#nomethod,IJHgrSupportAssemblyItem,IJHgrSupportType,IJModelLocate
'#nomethod,IJHgrSystem,IJMTOInfo,IJResponsibilityInfo,IJWeightCGGrouping,IJStructuralSystem
'#nomethod,IJRtePiping,IJGeometry,IJOccurrence,IJCommonObjects
Public Function outputIJHgrPipeSupport(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJRteCableSegmentPathFeat(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJRteCompOccur(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJDGeometry(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJLocalCoordinateSystem(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJRteCablewayCommon(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJRteCablewayStraightPathFeat(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJRteHeaderPathFeat(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJRteMaxCableFillInfo(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJWBSItemChild(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJWBSProjectChild(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJRteCableTrayOccur(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJCoatingInfo(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJCUHASHgrAisc_CO(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJHgrChild(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJHgrComponentItem(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJHgrSupportItem(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJUAHgrMiterOcc(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJUAHgrOccLength(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJUAHgrOccOverLength(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJUAHgrOccStructuralPart(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJHgrBOMDefinition(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJUAHgrCardinalPointProp(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJHgrDesignSupport(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJUASlabCompositionType(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputISPSSlabClassification(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJUASlabGeneralType(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJGraphicEntity(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJRteCablewayEndPathFeat(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJAppConnectionNotification(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJConstructionInfo(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJCUHASPipeDesignedO(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJFabricationInfo(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJHgrMirrorReflectBits(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJHgrRestraintProperties(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJHgrSupportAssemblyItem(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJHgrSupportType(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJModelLocate(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJHgrSystem(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJMTOInfo(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJResponsibilityInfo(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJWeightCGGrouping(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJStructuralSystem(Form As Object, Node1 As Node, o As Object) As Long
End Function
Public Function outputIJRtePiping(Form As Object, Node1 As Node, o As Object) As Long
End Function

'#endnomethod

Public Sub Publish(colActions As Collection)
    Dim s As String
    On Error GoTo Handler
'#colActions
     s = "IJHgrPipeSupport"
     colActions.Add Me, s
     s = "IJRteCableSegmentPathFeat"
     colActions.Add Me, s
     s = "IJRteCompOccur"
     colActions.Add Me, s
     s = "IJDGeometry"
     colActions.Add Me, s
     s = "IJLocalCoordinateSystem"
     colActions.Add Me, s
     s = "IJRteCablewayCommon"
     colActions.Add Me, s
     s = "IJRteCablewayStraightPathFeat"
     colActions.Add Me, s
     s = "IJRteHeaderPathFeat"
     colActions.Add Me, s
     s = "IJRteMaxCableFillInfo"
     colActions.Add Me, s
     s = "IJWBSItemChild"
     colActions.Add Me, s
     s = "IJWBSProjectChild"
     colActions.Add Me, s
     s = "IJRteCableTrayOccur"
     colActions.Add Me, s
     s = "IJCoatingInfo"
     colActions.Add Me, s
     s = "IJCUHASHgrAisc_CO"
     colActions.Add Me, s
     s = "IJHgrChild"
     colActions.Add Me, s
     s = "IJHgrComponentItem"
     colActions.Add Me, s
     s = "IJHgrSupportItem"
     colActions.Add Me, s
     s = "IJUAHgrMiterOcc"
     colActions.Add Me, s
     s = "IJUAHgrOccLength"
     colActions.Add Me, s
     s = "IJUAHgrOccOverLength"
     colActions.Add Me, s
     s = "IJUAHgrOccStructuralPart"
     colActions.Add Me, s
     s = "IJHgrBOMDefinition"
     colActions.Add Me, s
     s = "IJUAHgrCardinalPointProp"
     colActions.Add Me, s
     s = "IJHgrDesignSupport"
     colActions.Add Me, s
     s = "IJUASlabCompositionType"
     colActions.Add Me, s
     s = "ISPSSlabClassification"
     colActions.Add Me, s
     s = "IJUASlabGeneralType"
     colActions.Add Me, s
     s = "IJGraphicEntity"
     colActions.Add Me, s
     s = "IJRteCablewayEndPathFeat"
     colActions.Add Me, s
     s = "IJAppConnectionNotification"
     colActions.Add Me, s
     s = "IJConstructionInfo"
     colActions.Add Me, s
     s = "IJCUHASPipeDesignedO"
     colActions.Add Me, s
     s = "IJFabricationInfo"
     colActions.Add Me, s
     s = "IJHgrMirrorReflectBits"
     colActions.Add Me, s
     s = "IJHgrRestraintProperties"
     colActions.Add Me, s
     s = "IJHgrSupportAssemblyItem"
     colActions.Add Me, s
     s = "IJHgrSupportType"
     colActions.Add Me, s
     s = "IJModelLocate"
     colActions.Add Me, s
     s = "IJHgrSystem"
     colActions.Add Me, s
     s = "IJMTOInfo"
     colActions.Add Me, s
     s = "IJResponsibilityInfo"
     colActions.Add Me, s
     s = "IJWeightCGGrouping"
     colActions.Add Me, s
     s = "IJStructuralSystem"
     colActions.Add Me, s
     s = "IJRtePiping"
     colActions.Add Me, s
'#endcolActions
Exit Sub
Handler:
    Call mylog("Duplicate Definition for Interface: " & s)
    Resume Next
End Sub

'''' The Display method is not used any more!!
'''Public Sub Display(Form As frmShowElement, Node0 As MSComctlLib.Node, o As Object, sIntName As String)
'''    Select Case sIntName
''''#case
'''
''''#endcase
'''    Case Else
'''
'''    End Select
'''
'''End Sub
 



